api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
  # Usuários
  path('usuarios/', views.UsuarioListCreate.as_view(), name='usuario-create-view'),
  path(
    'usuarios/<int:pk>/', 
    views.UsuarioRetrieveUpdateDestroy.as_view(), 
    name='usuario-detail'
  ),

  # Chamado
  path('chamado/', views.ChamadoListCreate.as_view(), name='chamado-create-view'),
  path(
    'chamado/<int:pk>/', 
    views.ChamadoRetrieveUpdateDestroy.as_view(), 
    name='chamado-detail'
  ),

  # Anexo
  path('anexo/', views.AnexoListCreate.as_view(), name='anexo-create-view'),
  path(
    'anexo/<int:pk>/', 
    views.AnexoRetrieveUpdateDestroy.as_view(), 
    name='anexo-detail'
  ),
]

autenticacao/urls.py
from django.urls import path
from . import views

app_name = 'autenticacao'

urlpatterns = [
  path('', views.cadastro_views, name='cadastro'),
  path('login/', views.login_views, name='login'),
]

helpdesk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('autenticacao.urls')),
    path('api/', include('api.urls')),
]

api/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
  nome = models.CharField(max_length=100)
  email = models.EmailField(unique=True)
  telefone = models.CharField(max_length=20)
  departamento = models.CharField(max_length=150)
  cargo = models.CharField(max_length=100)

  USERNAME_FIELD = "email"
  username = None
  REQUIRED_FIELDS = ["username"]

  def __str__(self) -> str:
    return self.nome


class Chamado(models.Model):

  STATUS_CHOICES = [
    ('ABERTO', 'Aberto'),
    ('ANDAMENTO', 'Em Andamento'),
    ('RESOLVIDO', 'Resolvido')
  ]

  PRIORIDADES_CHOICES = [
    ('BAIXA', 'Baixa'),
    ('MEDIA', 'Média'),
    ('ALTA', 'Alta')
  ]

  CATEGORIAS_CHOICES = [
    ('HARDWARE', 'Problema de Hardware'),
    ('SOFTWARE', 'Problema de Software'),
    ('DUVIDA', 'Dúvida'),
    ('OUTROS', 'Outros')
  ]

  titulo = models.CharField(max_length=150)
  descricao = models.TextField()
  data = models.DateField(auto_now_add=True)
  status = models.CharField(max_length=15, choices=STATUS_CHOICES, default='ABERTO')
  categoria = models.CharField(max_length=20, choices=CATEGORIAS_CHOICES)
  prioridade = models.CharField(max_length=10, choices=PRIORIDADES_CHOICES)
  usuario = models.ForeignKey('Usuario', on_delete=models.SET_NULL, null=True)

  def __str__(self) -> str:
    return self.titulo


class Anexo(models.Model):
  nome_do_arquivo = models.CharField(max_length=255)
  caminho_do_arquivo = models.FileField(upload_to='anexos/')
  id_chamado = models.ForeignKey('Chamado', on_delete=models.CASCADE)

  def __str__(self) -> str:
    return self.nome_do_arquivo

autenticacao/models.py
from django.db import models

# Create your models here.

autenticacao/forms.py
from django import forms
from api.models import Usuario

class UsuarioForm(forms.ModelForm):
  class Meta:
    model = Usuario
    fields = [
      "id", 
      "nome", 
      "email",
      "telefone", 
      "departamento", 
      "cargo",
      "password"
    ]

    widgets = {
      'username': forms.TextInput(attrs={'class': 'form-control'}),
      'email': forms.EmailInput(attrs={'class': 'form-control'}),
      'first_name': forms.TextInput(attrs={'class': 'form-control'}),
      'last_name': forms.TextInput(attrs={'class': 'form-control'}),
      'telefone': forms.TextInput(attrs={'class': 'form-control'}),
      'departamento': forms.TextInput(attrs={'class': 'form-control'}),
      'cargo': forms.TextInput(attrs={'class': 'form-control'}),
      'password': forms.PasswordInput(attrs={'class': 'form-control'})
    }

    labels = {
      'nome': 'Nome Completo',
      'email': 'E-mail',
      'telefone': 'Telefone',
      'departamento': 'Departamento',
      'cargo': 'Crago',
      'password': 'Senha',
    }

api/views.py
from rest_framework import generics

from .models import Usuario, Chamado, Anexo
from .serializers import UsuarioSerializer, ChamadoSerializer, AnexoSerializer


class UsuarioListCreate(generics.ListCreateAPIView):
  queryset = Usuario.objects.all()
  serializer_class = UsuarioSerializer

class UsuarioRetrieveUpdateDestroy(generics.RetrieveUpdateDestroyAPIView):
  queryset = Usuario.objects.all()
  serializer_class = UsuarioSerializer
  lookup_field = "pk"


class ChamadoListCreate(generics.ListCreateAPIView):
  queryset = Chamado.objects.all()
  serializer_class = ChamadoSerializer

class ChamadoRetrieveUpdateDestroy(generics.RetrieveUpdateDestroyAPIView):
  queryset = Chamado.objects.all()
  serializer_class = ChamadoSerializer
  lookup_field = "pk"

class AnexoListCreate(generics.ListCreateAPIView):
  queryset = Anexo.objects.all()
  serializer_class = AnexoSerializer

class AnexoRetrieveUpdateDestroy(generics.RetrieveUpdateDestroyAPIView):
  queryset = Anexo.objects.all()
  serializer_class = AnexoSerializer
  lookup_field = "pk"

autenticacao/views.py
from django.shortcuts import render, redirect
from .forms import UsuarioForm
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth import get_user_model

def cadastro_views(request):
  if request.method == 'POST':
    form = UsuarioForm(request.POST)

    if form.is_valid():
      user = form.save(commit=False)
      user.set_password(form.cleaned_data["password"])
      user.save()
      return redirect('autenticacao:login')
  
  else:
    form = UsuarioForm()
  
  return render(request, 'autenticacao/cadastro.html', {'form': form})

def login_views(request):
  if request.method == 'POST':
    email = request.POST['email']
    password = request.POST['password']

    User = get_user_model()
    print(User.objects.all().values('email'))
    user = authenticate(request, email=email, password=password)

    if user is not None:
      login(request, user)
      return redirect('api:chamado-create-view')

    else:
      messages.error(request, 'Credenciais Inválidas')

  return render(request, 'autenticacao/login.html')

autenticacao/templates/autenticacao/cadastro.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  </head>
  <body>
    <div class="container">
      <h1 class="mt-5">Cadastro</h1>
      <form method="POST" class="mt-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Cadastrar</button>

        <div class="text-center mt-3">
          <p>Já tem uma conta? <a href="{% url 'autenticacao:login' %}">Login</a></p>
        </div>
      </form>
    </div>
  </body>
</html>

autenticacao/templates/autenticacao/login.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  </head>
  <body>
    <div class="login-container">
      <h2>Login</h2>

      <form method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="email">Email:</label>
          <input type="email" id="email" name="email" class="form-control" required>
        </div>

        <div class="form-group">
          <label for="password">Senha:</label>
          <input type="password" id="password" name="password" class="form-control" required>
        </div>

        <button type="submit" class="btn btn-primary">Entrar</button>

        <div class="text-center mt-3">
          <p>Não tem conta? <a href="{% url 'autenticacao:cadastro' %}">Cadastra-se</a></p>
        </div>
      </form>
    </div>
  </body>
</html>